services:
  postgres:
    image: postgres:17-alpine
    container_name: pilotes-db
    environment:
      POSTGRES_DB: pilotes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

#  app:
#    build: .
#    container_name: pilotes-app
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pilotes
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: postgres
#    ports:
#      - "8080:8080"
#    restart: always

volumes:
  postgres_data:
